name: comment on issue after label
permissions:
  contents: read

on:
  pull_request_target:
    types:
      - labeled

jobs:
  
  post_comment:
    name: post_comment
    runs-on: ubuntu-latest
    if: contains(github.event.pull_request.labels.*.name, 'question')
    permissions:
      pull-requests: write
      #issues: write
    
    steps:
      - name: verify if worked
        run: echo label set

      - name: comment
        env:
          ISSUE_NUMBER: ${{ github.event.pull_request.number }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh api \
          --method POST \
          -H "Accept: application/vnd.github+json" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          /repos/StefanieSenger/GitHub-Actions-test-repo/issues/ISSUE_NUMBER/comments \
          -f 'body=The question label was set?'
