# .github/workflows/create_artifact.yml

name: create_artifact
# This workflow saves the current date into a file and the weekday into another file on
# the condition on which weekday it is and uploads both files as artifacts if they
# exist. These files can then be downloaded in the actions tab.

on:
  push:
    branches: [ "main" ]

jobs:

  print_date:
    runs-on: ubuntu-latest

    steps:
      - name: checkout repository
        uses: actions/checkout@v4

      # step is not necessary for the artifacts, but just to show that it runs
      - name: print date
        run: echo "Current date and time $(date)"

      - name: save date
        run: date +"%H:%M:%S" > timestamp.txt

      - name: save weekday on condition
        run: |
          WEEKDAY=$(date +%A)
          if [[ "$WEEKDAY" != "Saturday" && "$WEEKDAY" != "Sunday" ]]; then
            echo "$WEEKDAY" > weekday.txt
          fi

      - name: upload artifact for date
        uses: actions/upload-artifact@v4
        with:
          name: timestamp
          path: timestamp.txt

      - name: upload artifact for weekday if available
        # the if checks if file exists:
        if: hashFiles('weekday.txt') != ''
        uses: actions/upload-artifact@v4
        with:
          name: weekday
          path: weekday.txt