name: setup and run test suite
# This workflow installs a specific python version in the runner, installs conda and
# pytest and runs the extensive test suite.

on:
  push:
    branches: [ "main" ]

jobs:
  setup_and_run_test_suite:
    runs-on: ubuntu-latest

    steps:

      - name: Check out repository
        uses: actions/checkout@v4

      - name: install python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13.2'

      - name: print python version
        run: python --version

      - name: set up conda
        uses: conda-incubator/setup-miniconda@v3

      - name: install environment and run test suite
        run: |
          conda create --yes --name conda_environment pytest
          conda run --name conda_environment pytest tests/test_file.py
          
        # this step fails with "CondaError: Run 'conda init' before 'conda activate'" ...
        # seems I cannot fix it without learning more about conda first