name: using_matrix

on:
  push:
    branches: [ "main" ]

jobs:
  matrix_job:
    fail-fast: false
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - name: matrix_for_ubuntu
            os: ubuntu-24.04
            ENVIRONMENTAL_VARIABLE: this_is_our_environmental_variable_for_ubuntu
          - name: matrix_for_mac_os
            os: macos-13
            ENVIRONMENTAL_VARIABLE: this_is_our_environmental_variable_for_mac_os
    
    env:
      ENVIRONMENTAL_VARIABLE: ${{ matrix.ENVIRONMENTAL_VARIABLE }}

    steps:
      - name: print os
        run: echo ${{ matrix.os }}

      - name: print environmental variable
        run: echo $ENVIRONMENTAL_VARIABLE