name: matrix_with_output

# on:
#   push:
#     branches: [ "main" ]

# to prevent it from running every time:
on:
  pull_request:

jobs:
  matrix_job:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: matrix_for_ubuntu
            os: ubuntu-latest
            ENVIRONMENTAL_VARIABLE: this_is_our_environmental_variable_for_ubuntu
          - name: matrix_for_mac_os
            os: macOS-latest
            ENVIRONMENTAL_VARIABLE: this_is_our_environmental_variable_for_mac_os
          - name: matrix_for_windows
            os: windows-latest
            ENVIRONMENTAL_VARIABLE: this_is_our_environmental_variable_for_windows
    
    env:
      ENVIRONMENTAL_VARIABLE: ${{ matrix.ENVIRONMENTAL_VARIABLE }}

    steps:
      - name: print os
      # os_name is the defined output name
        run: |
          echo ${{ runner.os }}
          echo "os_name=${{ runner.os }}" >> $GITHUB_OUTPUT
        id: test_id

      - name: print environmental variable
        run: echo $ENVIRONMENTAL_VARIABLE

      - name: reprint os if windows
        if: steps.test_id.os_name == 'Windows'
        run: echo ${{ runner.os }}