name: matrix_with_ccache

on:
  push:
    branches: [ "main" ]

jobs:
  matrix_job:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: matrix_for_ubuntu
            os: ubuntu-latest
            ENVIRONMENTAL_VARIABLE: this_is_our_environmental_variable_for_ubuntu
          - name: matrix_for_mac_os
            os: macOS-latest
            ENVIRONMENTAL_VARIABLE: this_is_our_environmental_variable_for_mac_os
          - name: matrix_for_windows
            os: windows-latest
            ENVIRONMENTAL_VARIABLE: this_is_our_environmental_variable_for_windows
          - name: matrix_for_ubuntu_2
            os: ubuntu-latest
            ENVIRONMENTAL_VARIABLE: this_is_our_environmental_variable_for_ubuntu_2
    
    env:
      ENVIRONMENTAL_VARIABLE: ${{ matrix.ENVIRONMENTAL_VARIABLE }}

    steps:
      - name: print os
        run: echo ${{ runner.os }}

      - name: Check out repository
        uses: actions/checkout@v4

      # hopefully fixes windows issue:
      - name: Configure compiler for ccache
        shell: bash
        run: |
          export CC="ccache gcc"
          export CXX="ccache g++"

      - name: create cache for ccache
        uses: actions/cache@v4
        id: ccache_id
        with:
          path: .ccache
          key: ${{ runner.os }}-ccache- # key is unique identifier used the access this cache
          #restore-keys: ${{ runner.os }}-ccache- # fallback keys

      - name: set up conda
        uses: conda-incubator/setup-miniconda@v3

      - name: print python version
        run: python --version

      - name: print environmental variable
        run: echo $ENVIRONMENTAL_VARIABLE

      - name: compile if not ccached
        if: ${{ steps.ccache_id.outputs.cache-hit != 'true' }}
        run: echo Compiling...

      - name: Compile C code
        run: gcc scr/hello.c -o hello

      - name: show ccache Statistics
        run: ccache --show-stats

      - name: install environment and run test suite
        run: |
          conda create --yes --name conda_environment pytest ccache
          conda run --name conda_environment pytest tests/test_file.py
